V1 ;IW-TS,VV1,MVTS V9.10;15/6/96;UTILITY
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1978-1996
 ;
 I $D(^VENVIRON("OUTPUT OPEN"))=1 O ^VENVIRON("OUTPUT OPEN")
 I $D(^VENVIRON("INPUT OPEN"))=1 O ^VENVIRON("INPUT OPEN")
 I $D(^NEXT)=1 G NEXTNEXT
 I $D(^VREPORT("Part-77"))=0 G ^VV1
 F ABSN=12150:-1:12111 I $D(^VREPORT("Part-77",ABSN,"NEXT"))=1 G NEXT
 F KK=8:-1:1 S ABSN="OPT0"_KK I $D(^VREPORT("Part-77",ABSN,"NEXT"))=1 G NEXT
 F ABSN=12110:-1:10001 I $D(^VREPORT("Part-77",ABSN,"NEXT"))=1 G NEXT
 G ^VV1
NEXT I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 D @^VREPORT("Part-77",ABSN,"NEXT")
 Q
NEXTNEXT I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 D @^NEXT Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
