V1BR1 ;IW-YS-KO-TS,V1BR,MVTS V9.10;15/6/96;BREAK COMMAND
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1978-1996
 S ^VCOMP=^VCOMP_"B" W !!,"TEST 5: *BREAK*  Enter the resuming command --> : " BREAK  S ^VCOMP=^VCOMP_"C"
 G EOR
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
EOR ;end of eor
