V1CALLE ;IW-KO-TS,V1CALL,MVTS V9.10;15/6/96;DO (CALL) COMMAND
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1978-1996
1 S ^VCOMP=^VCOMP_"1 " Q  S ^VCOMP=^VCOMP_"QUIT ERROR"
2 S ^VCOMP=^VCOMP_"2 " Q
3 S ^VCOMP=^VCOMP_"3 " Q
4 S ^VCOMP=^VCOMP_"4 " Q
5 S ^VCOMP=^VCOMP_"5 " Q
6 S ^VCOMP=^VCOMP_"6 " Q
7 S ^VCOMP=^VCOMP_"7 " Q  ;V1CALLE+8
8 S ^VCOMP=^VCOMP_"8 " Q
9 S ^VCOMP=^VCOMP_"9 " Q
10 S ^VCOMP=^VCOMP_"10 " Q
%ABC S ^VCOMP=^VCOMP_"%ABC " QUIT
AABBCC S ^VCOMP=^VCOMP_"AABBCC " Q
%0000000 S ^VCOMP=^VCOMP_"%0000000 " Q
012 S ^VCOMP=^VCOMP_"012 " QUIT
 S ^VCOMP=^VCOMP_"ZXY987A0 " Q
Z S ^VCOMP=^VCOMP_"Z " Q
% S ^VCOMP=^VCOMP_"% " Q
%2345678 S ^VCOMP=^VCOMP_"%2345678 " Q
 S ^VCOMP=^VCOMP_"%A1B2C3D " Q
 S ^VCOMP=^VCOMP_"Q " Q
 S ^VCOMP=^VCOMP_"%A1 " Q
DO S ^VCOMP=^VCOMP_"DO "
 QUIT
12 S ^VCOMP=^VCOMP_"12 " Q
 S ^VCOMP=^VCOMP_"%A " Q
 S ^VCOMP=^VCOMP_"100 " Q
IF S ^VCOMP=^VCOMP_"IF " Q
 S ^VCOMP=^VCOMP_"%0 " Q
 S ^VCOMP=^VCOMP_"Z012A " Q
ABCDEFGH S ^VCOMP=^VCOMP_"ABCDEFGH " Q
0 S ^VCOMP=^VCOMP_"0 " Q
 QUIT
 S ^VCOMP=^VCOMP_"1 " Q
 S ^VCOMP=^VCOMP_"01 " QUIT
%0A1B2C3 S ^VCOMP=^VCOMP_"%0A1B2C3 " Q
 S ^VCOMP=^VCOMP_"%90 " Q
 S ^VCOMP=^VCOMP_"0012 " Q
 S ^VCOMP=^VCOMP_"10 " Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
