V1PC1 ;IW-YS-MM-TS,V1PC,MVTS V9.10;15/6/96;POST-CONDITIONALS
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1978-1996
 S ^VCOMP=^VCOMP_"^V1PC1"_I_" " Q  ;+3 844 839
 ;
BUG S ^VCOMP=^VCOMP_"^V1PC1_BUG " Q
OS S ^VCOMP=^VCOMP_"OS " Q  ;845
 S ^VCOMP=^VCOMP_"OS+1 " Q  ;846
 S ^VCOMP=^VCOMP_"OS+2 " Q  ;846
 S ^VCOMP=^VCOMP_"OS+3 " Q  ;846
 S ^VCOMP=^VCOMP_"OS+4 " Q
 S ^VCOMP=^VCOMP_"OS+5 " Q
%DRAFT S ^VCOMP=^VCOMP_"%DRAFT "
 S ^VCOMP=^VCOMP_"%DRAFT+1 " Q  ;841
 S ^VCOMP=^VCOMP_"%DRAFT+2 " Q
 S ^VCOMP=^VCOMP_"%DRAFT+3 " G:$P("A^B^C","^",2)="1" BUG+2^V1PC1,BUG+1 ;841
 S ^VCOMP=^VCOMP_"%DRAFT+4 " G GO1^V1PCB Q  ;841
FILE S ^VCOMP=^VCOMP_"FILE " Q  ;845
010 S ^VCOMP=^VCOMP_"010 " Q  ;845
A S ^VCOMP=^VCOMP_"A " G A+1^V1PC1:$D(^V1PC1),LABEL^V1PCB:1 Q  ;840
B S ^VCOMP=^VCOMP_"B " Q  ;840 (test corrected in V7.3;20/6/88)
C S ^VCOMP=^VCOMP_"C" Q
D S ^VCOMP=^VCOMP_"D " G:$T(V1PC1+300)="" 0010^V1PCB:12300=00123E2,BUG^V1PC1 Q
E S ^VCOMP=^VCOMP_"E" Q
F S ^VCOMP=^VCOMP_"F " Q  ;840
G S ^VCOMP=^VCOMP_"G" Q
H S ^VCOMP=^VCOMP_"H" Q
I S ^VCOMP=^VCOMP_"I" Q
J S ^VCOMP=^VCOMP_"J" Q
K S ^VCOMP=^VCOMP_"K" Q
L S ^VCOMP=^VCOMP_"L" Q
M S ^VCOMP=^VCOMP_"M" Q
N S ^VCOMP=^VCOMP_"N" Q
O S ^VCOMP=^VCOMP_"O" Q  ;846
P S ^VCOMP=^VCOMP_"P" Q  ;846
Q S ^VCOMP=^VCOMP_"Q" Q  ;846
R S ^VCOMP=^VCOMP_"R" Q  ;846
S S ^VCOMP=^VCOMP_"S" Q  ;846
T S ^VCOMP=^VCOMP_"T" Q  ;846
U S ^VCOMP=^VCOMP_"U" Q  ;846
V S ^VCOMP=^VCOMP_"V" Q  ;846
W S ^VCOMP=^VCOMP_"W" Q
X S ^VCOMP=^VCOMP_"X" Q
Y S ^VCOMP=^VCOMP_"Y" Q
Z S ^VCOMP=^VCOMP_"Z" Q
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
 ;
GO1 S ^VCOMP=^VCOMP_1 Q
 S ^VCOMP=^VCOMP_2 Q
 S ^VCOMP=^VCOMP_2 G GO2^V1PCB ;841
ENTER S ^VCOMP=^VCOMP_"---3 " ;715
ENTERY S ^VCOMP=^VCOMP_"4 " Q  ;715
GO2 S ^VCOMP=^VCOMP_5 Q
 S ^VCOMP=^VCOMP_6 Q
 S ^VCOMP=^VCOMP_7 Q
 S ^VCOMP=^VCOMP_8 Q
 S ^VCOMP=^VCOMP_4 G GO3^V1PCB ;841
GO3 S ^VCOMP=^VCOMP_3 Q
 S ^VCOMP=^VCOMP_9 Q
 S ^VCOMP=^VCOMP_0 Q
 S ^VCOMP=^VCOMP_6 Q  ;841
ABCDEFGH S ^VCOMP=^VCOMP_"ABCDEFGH " Q
 S ^VCOMP=^VCOMP_"ABCDEFGH+1 " Q  ;846
 S ^VCOMP=^VCOMP_"ABCDEFGH+2 " Q
 S ^VCOMP=^VCOMP_"ABCDEFGH+3 " Q
 S ^VCOMP=^VCOMP_"ABCDEFGH+4 " Q
 ;
END S ^VCOMP=^VCOMP_"!"
