V1PRESET ;IW-TS,VV1,MVTS V9.10;15/6/96;UTILITY
 ;
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1984-1996
 S ^VREPORT("Part-77",^ABSN)="*ABORT*"
 S ^VREPORT("Part-77",^ABSN,"ITEM")=^ITEM
 S ^VREPORT("Part-77",^ABSN,"NEXT")=^NEXT
 Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
