V1PRGD3 ;IW-YS-TS,V1PRGD,MVTS V9.10;15/6/96;PRELIMINARY TEST OF GOTO, DO AND QUIT (EXPLICIT AND IMPLICIT) COMMANDS
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1978-1996
 S VCOMP=VCOMP_1 D A
 S VCOMP=VCOMP_3 G B
 S VCOMP=VCOMP_"ERROR2" QUIT
 Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
 ;
A S VCOMP=VCOMP_2 Q
B S VCOMP=VCOMP_4
