V2 ;IW-TS,VV2,MVTS V9.10;15/6/96;UTILITY
 ;
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1984-1996
 ;
 I $D(^VENVIRON("OUTPUT OPEN"))=1 O ^VENVIRON("OUTPUT OPEN")
 I $D(^VENVIRON("INPUT OPEN"))=1 O ^VENVIRON("INPUT OPEN")
 I $D(^NEXT)=1 G NEXTNEXT
 I $D(^VREPORT("Part-84"))=0 G ^VV2
 F ABSN=20224:-1:20001 I $D(^VREPORT("Part-84",ABSN,"NEXT"))=1 G NEXT
 K  G ^VV2
NEXT I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 D @^VREPORT("Part-84",ABSN,"NEXT")
 Q
NEXTNEXT I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 D @^NEXT Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
