V3DWPE(X,Y) ;IW-KO-YS-TS,V3DWP,MVTS V9.10;15/6/96;PART-90
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1990-1996
 ;
 S ^VCOMP=^VCOMP_$d(X) I $D(X)#10=1 S ^VCOMP=^VCOMP_X
 S ^VCOMP=^VCOMP_$d(Y) I $D(Y)#10=1 S ^VCOMP=^VCOMP_Y
 i 0
 K Y
 S X="x",Y="y" Q
AB(X,Y,Z) ;
 S ^VCOMP=^VCOMP_$d(X) I $D(X)#10=1 S ^VCOMP=^VCOMP_X
 S ^VCOMP=^VCOMP_$d(Y) I $D(Y)#10=1 S ^VCOMP=^VCOMP_Y
 S ^VCOMP=^VCOMP_$d(Z) I $D(Z)#10=1 S ^VCOMP=^VCOMP_Z
 S ^VCOMP=^VCOMP_$d(W) I $D(W)#10=1 S ^VCOMP=^VCOMP_W
 K Y
 S X="x",Y="y",W="w"
 Q
A0(A,B,C,D,E,F,G) ;
 S ^VCOMP=^VCOMP_$D(A)      I $D(A)#10=1 S ^VCOMP=^VCOMP_A
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(A(1))   I $D(A(1))#10=1 S ^VCOMP=^VCOMP_A(1)
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(B)      I $D(B)#10=1 S ^VCOMP=^VCOMP_B
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(B(2,3)) I $D(B(2,3))#10=1 S ^VCOMP=^VCOMP_B(2,3)
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(C)      I $D(C)#10=1 S ^VCOMP=^VCOMP_C
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(C("A")) I $D(C("A"))#10=1 S ^VCOMP=^VCOMP_C("A")
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(D)      I $D(D)#10=1 S ^VCOMP=^VCOMP_D
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(D(1,2,3)) I $D(D(1,2,3))#10=1 S ^VCOMP=^VCOMP_D(1,2,3)
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(E)      I $D(E)#10=1 S ^VCOMP=^VCOMP_E
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(F)      I $D(F)#10=1 S ^VCOMP=^VCOMP_F
 S ^VCOMP=^VCOMP_" "
 S ^VCOMP=^VCOMP_$D(G)      I $D(G)#10=1 S ^VCOMP=^VCOMP_G
 S ^VCOMP=^VCOMP_"/"
 Q
T(X,Y) ;
 S ^VCOMP=^VCOMP_$d(X) I $D(X)#10=1 S ^VCOMP=^VCOMP_X
 S ^VCOMP=^VCOMP_$d(Y) I $D(Y)#10=1 S ^VCOMP=^VCOMP_Y
 i 0
 S ^VCOMP=^VCOMP_" "_$T
 K Y
 S X="x",Y="y"
 Q
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
