V3LOCKD ;IW-KO-YS-TS,V3LOCK,MVTS V9.10;15/6/96;PART-90
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1990-1996
 LOCK ^VF
 S ^VE=1
 LOCK +(^VB,^VD,^VC)
 S ^VA=^VA+^VB+^VC
 LOCK
 H
 ;
V3LOCKDT ;
 LOCK ^VF
 S ^VE=1
 LOCK +(^VB,^VD,^VC,^VE)
 S ^VA=^VA+^VB+^VC+^VD
 LOCK
 H
 ;
V3LOCKMD ;
 LOCK ^VF
 S ^VE=1
 LOCK +^VA
 S ^VA=^VA*10
 LOCK +^VB
 S ^VA=^VA+^VB
 LOCK
 HALT
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
