V3SSUB1 ;IW-KO-TS,VV3,MVTS V9.10;15/6/96;STRING SUBSCRIPT -1-
 ;
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1984-1996
 W !!,"       Moved from V2SSUB1"
 W !!,"32---V3SSUB1: String subscript -1-",!
 ;
1 W !,"II,III-350  Length of one subscript of a local variable is 63 (max)"
 ;(title corrected in V7.4;16/9/89)
 S ^ABSN="30350",^ITEM="II,III-350  Length of one subscript of a local variable is 63 (max)"
 S ^NEXT="2^V3SSUB1,V3SSUB2^V3SSUB,V3JOB^VV3" D ^V3PRESET
 S VCOMP="" S MAX="#" F I=0:2:252 S MAX=MAX_"QW"
 S ABC("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")=1
 S VCOMP=ABC("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")
 S ABC("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")=MAX
 S VCOMP=VCOMP_(ABC("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")=MAX) K ABC
 S ^VCOMP=VCOMP,^VCORR="11" D ^VEXAMINE
 ;
2 W !,"II,III-351  Total length of a local variable is 127 (max)"
 ;(title corrected in V7.4;16/9/89)
 S ^ABSN="30351",^ITEM="II,III-351  Total length of a local variable is 127 (max)"
 S ^NEXT="3^V3SSUB1,V3SSUB2^V3SSUB,V3JOB^VV3" D ^V3PRESET
 S VCOMP="" S MAX="#" F I=0:2:252 S MAX=MAX_"QW"
 S ABCDEFGH("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO")=2
 S VCOMP=ABCDEFGH("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO")
 S ABCDEFGH("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO")=MAX
 S VCOMP=VCOMP_(ABCDEFGH("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO")=MAX) K ABCDEFGH
 S ^VCOMP=VCOMP,^VCORR="21" D ^VEXAMINE
 ;
3 W !,"II,III-352  Length of one subscript of a global variable is 63 (max)"
 ;(title corrected in V7.4;16/9/89)
 S ^ABSN="30352",^ITEM="II,III-352  Length of one subscript of a global variable is 63 (max)"
 S ^NEXT="4^V3SSUB1,V3SSUB2^V3SSUB,V3JOB^VV3" D ^V3PRESET
 S VCOMP="" S MAX="#" F I=0:2:252 S MAX=MAX_"QW"
 S ^VV("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")=3
 S VCOMP=^VV("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")
 S ^VV("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")=MAX
 S VCOMP=VCOMP_(^VV("ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'ABCDEFGHIJKLMNOPQRSTUVWXYZ#$%&'2")=MAX)
 S ^VCOMP=VCOMP,^VCORR="31" D ^VEXAMINE K ^VV
 ;
4 W !,"II,III-353  Total length of a global variable is 127 (max)"
 ;(title corrected in V7.4;16/9/89)
 S ^ABSN="30353",^ITEM="II,III-353  Total length of a global variable is 127 (max)"
 S ^NEXT="V3SSUB2^V3SSUB,V3JOB^VV3" D ^V3PRESET
 S VCOMP="" S MAX="#" F I=0:2:252 S MAX=MAX_"QW"
 S ^VV("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","BCDE")=4
 S VCOMP=^VV("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","BCDE")
 S ^VV("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","BCDE")=MAX
 S VCOMP=VCOMP_(^VV("ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","ABCDEFGHIJKLMNO","BCDE")=MAX)
 S ^VCOMP=VCOMP,^VCORR="41" D ^VEXAMINE K ^VV
 ;
END W !!,"End of 32 --- V3SSUB1",!
 K  K ^VV Q
 Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
