V4 ;IW-KO-YS-TS,VV4/VV4TP,MVTS V9.10;15/6/96;UTILITY
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1984-1996
 ;
 I $D(^VENVIRON("OUTPUT OPEN"))=1 O ^VENVIRON("OUTPUT OPEN")
 I $D(^VENVIRON("INPUT OPEN"))=1 O ^VENVIRON("INPUT OPEN")
 I $D(^NEXT)=1 G NEXTNEXT
 I $D(^VREPORT("Part-94"))=0 G ^VV4
 F ABSN=40923:-1:40001 I $D(^VREPORT("Part-94",ABSN,"NEXT"))=1 G NEXT
 K  G ^VV4
NEXT I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 I ABSN>40866,ABSN<40924 S ^HALT=1 LOCK  H 4
 D @^VREPORT("Part-94",ABSN,"NEXT")
 Q
NEXTNEXT I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 I ^NEXT["VV4TP" S ^HALT=1 LOCK  H 4
 D @^NEXT Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
