V4JOBEXA(X,Y) ;IW-KO-YS-TS,V4JOB,MVTS V9.10;15/6/96;
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1990-1996
 ;
A ;
 L ^ABCDEF
 S V4JOB="LVN ERROR"
 S ^V4JOB=$J_" "_X_Y
 H
 ;
B(H) ;
 L ^ABCDEF
 S V4JOB="LVN ERROR"
 S ^V4JOB="OK "_H
 H
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
