V4PRIN ;IW-KO-TS-YS,VV4,MVTS V9.10;15/6/96;$PRINCIAPL
 ;
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1984-1996
 ;
 W !!,"119---V4PRIN:  $PRINCIPAL special variable name"
 ;
1 S ^ABSN="40743",^ITEM="IV-743  $PRINCIPAL value format"
 S ^NEXT="2^V4PRIN,V4QUIT^VV4" D ^V4PRESET K
 S ^VCOMP=($PRINCIPAL?1.E)_($principal?.E1.C.E)
 S ^VCORR="10" D ^VEXAMINE
 ;
2 S ^ABSN="40744",^ITEM="IV-744  $P value format"
 S ^NEXT="3^V4PRIN,V4QUIT^VV4" D ^V4PRESET K
 S ^VCOMP=($PRINCIPAL=$P)_($PRINCIPAL=$p)
 S ^VCORR="11" D ^VEXAMINE
 ;
3 S ^ABSN="40745",^ITEM="IV-745  change current device"
 S ^NEXT="4^V4PRIN,V4QUIT^VV4" D ^V4PRESET K
 S CURRENT=$IO,^VCOMP="SKIP"
 I $D(^VENVIRON("#1 OPEN"))=0 G SKIP
 I $D(^VENVIRON("#1 USE"))=0 G SKIP
 I $D(^VENVIRON("#1 CLOSE"))=0 G SKIP
 I CURRENT'=^VENVIRON("#1 USE") D  G CONT
 . O ^VENVIRON("#1 OPEN")
 . U ^VENVIRON("#1 USE")
 . S PRIN=$P
 . C ^VENVIRON("#1 CLOSE")
 ;
 I $D(^VENVIRON("#2 OPEN"))=0 G SKIP
 I $D(^VENVIRON("#2 USE"))=0 G SKIP
 I $D(^VENVIRON("#2 CLOSE"))=0 G SKIP
 I CURRENT'=^VENVIRON("#2 USE") D  G CONT
 . O ^VENVIRON("#2 OPEN")
 . U ^VENVIRON("#2 USE")
 . S PRIN=$P
 . C ^VENVIRON("#2 CLOSE")
CONT S ^VCOMP=(PRIN=CURRENT)
SKIP U CURRENT
 S ^VCORR="1" D ^VEXAMINE
 ;
4 S ^ABSN="40746",^ITEM="IV-746  the value of $PRINCIPAL is equal to the initial value of $IO"
 S ^NEXT="V4QUIT^VV4" D ^V4PRESET K  K ^V
 JOB PRIN::60
 IF $T F I=1:1:60 Q:$D(^V)#10=1  H 1
 I $D(^V)#10=0 S ^V="ERROR"_$C(22)_"error"
 S ^VCOMP=($P(^V,$C(22),1)=$P(^V,$C(22),2))_" "_($P(^V,$C(22),1)=$P)
 S ^VCORR="1 0" D ^VEXAMINE K ^V
 ;
END W !!,"End of 119 --- V4PRIN",!
 K  Q
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
 ;
PRIN ;
 S ^V=$PRINCIPAL_$C(22)_$IO
 Q
