V4READ1 ;IW-KO-YS-TS,V4READ,MVTS V9.10;15/6/96;PART-94
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1994-1996
 ;
 W !!,"93---V4READ1:  READ Command  -1-"
 ;
 W !!,"READ gvn"
A ;
1 W !!,"IV-613  READ gvn"
 S ^ABSN="40613",^ITEM="IV-613  READ gvn"
 S ^NEXT="2^V4READ1,V4READ2^V4READ,V4KEY^VV4" D ^V4PRESET K
 I $D(^VENVIRON("INPUT USE"))=1 U ^VENVIRON("INPUT USE")
 S ^VV=4
 READ !,"   READ ^VV : Type 3 characters 'ABC' and a <CR> : ",^VV
 S ^VCOMP=^VV,^VCORR="ABC"
 I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 D AGAIN^VEXAMINE I RES="YES" G A
 D ^VEXAMINE
B ;
2 W !!,"IV-614  $D(gvn)=0"
 S ^ABSN="40614",^ITEM="IV-614  $D(gvn)=0"
 S ^NEXT="3^V4READ1,V4READ2^V4READ,V4KEY^VV4" D ^V4PRESET K  K ^VV
 I $D(^VENVIRON("INPUT USE"))=1 U ^VENVIRON("INPUT USE")
 READ !,"   READ ^VV(1) : Type 3 characters 'XYZ' and a <CR> : ",^VV(1)
 S ^VCOMP=^VV(1)_$D(^VV)_$D(^VV(1))_$Q(^VV)_$Q(^VV(1)),^VCORR="XYZ101^VV(1)"
 I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 D AGAIN^VEXAMINE I RES="YES" G B
 D ^VEXAMINE
C ;
3 W !!,"IV-615  $D(gvn)=1"
 S ^ABSN="40615",^ITEM="IV-615  $D(gvn)=1"
 S ^NEXT="V4READ2^V4READ,V4KEY^VV4" D ^V4PRESET K  K ^VV
 I $D(^VENVIRON("INPUT USE"))=1 U ^VENVIRON("INPUT USE")
 S ^VV="abcd"
 READ !,"   READ ^VV : Type 1 character 'X' and a <CR> : ",^VV
 S ^VCOMP=^VV_$D(^VV)_$D(VV(1))_$Q(^VV),^VCORR="X10"
 I $D(^VENVIRON("OUTPUT USE"))=1 U ^VENVIRON("OUTPUT USE")
 D AGAIN^VEXAMINE I RES="YES" G C
 D ^VEXAMINE
 ;
END W !!,"End of 93 --- V4READ1",!
 K  Q
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
