V4TPE15 ;IW-KO-YS-TS,VV4TP,MVTS V9.10;15/7/96;PART-94 Transaction
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1994-1996
1 ;---TSTART lname  ... TRESTART ... TCOMMIT
 F  Q:$$^V4GETS1
 D ^V4TPS1
 TSTART VA
 IF $TRESTART G 151
 D ^V4TPCHK
 K ^VA
 K
 TRESTART
 TCOMMIT
 D ^V4TPCHK
 L  H
151 D ^V4TPCHK
 D ^V4TPS2
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
2 ;---TSTART (lname,lname)  ... TRESTART ... TCOMMIT
 F  Q:$$^V4GETS1
 D ^V4TPS2
 TSTART (VA,VC)
 IF $TRESTART G 152
 D ^V4TPCHK
 S ^VA(1,2)=123,^VB(2)=2,VB(2)="VB(2)",VC(1)="VC(1)" K VD
 TRESTART
 TCOMMIT
 D ^V4TPCHK
 L  H
152 D ^V4TPCHK
 D ^V4TPS4
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
3 ;---TSTART * ... TRESTART .. TCOMMIT
 F  Q:$$^V4GETS1
 D ^V4TPS2
 TSTART *
 IF $TRESTART=2 G 153
 D ^V4TPCHK
 S ^VC(1,2)="VC(1,2)",^VD="^VD"
 K  S VA(1)="VA(1)",VC="VC",VD(1)="VD(1)"
 TRESTART
 TCOMMIT
 D ^V4TPCHK
 L  H
153 D ^V4TPCHK
 D ^V4TPS1
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
4 ;---TSTART ()  ... TRESTART ... TCOMMIT
 F  Q:$$^V4GETS1
 D ^V4TPS3
 TSTART ()
 IF $TRESTART G 154
 D ^V4TPCHK
 K
 TRESTART
 TCOMMIT
 D ^V4TPCHK
 L  H
154 D ^V4TPCHK
 D ^V4TPS4
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
