V4TPE17 ;IW-KO-YS-TS,VV4TP,MVTS V9.10;15/7/96;PART-94 Transaction
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1994-1996
1 ;---TSTART .. TSTART .. TCOMMIT .. TCOMMIT
 F  Q:$$^V4GETS1
 D ^V4TPS1
 TSTART VA
 D ^V4TPCHK
 D ^V4TPS2
 TSTART VB
 D ^V4TPCHK
 D ^V4TPS1
 TCOMMIT
 D ^V4TPCHK
 D ^V4TPS2
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
2 ;---TSTART .. TSTART .. TROLLBACK
 F  Q:$$^V4GETS1
 D ^V4TPS1
 TSTART VA
 D ^V4TPCHK
 D ^V4TPS2
 TSTART VB
 D ^V4TPCHK
 D ^V4TPS1
 TROLLBACK
 D ^V4TPCHK
 L  H
 ;
3 ;---TSTART .. TSTART .. TRESTART .. TCOMMIT .. TCOMMIT
 F  Q:$$^V4GETS1
 D ^V4TPS1
 TSTART VA
 D ^V4TPS2
 TSTART *
 IF $TRESTART G 173
 D ^V4TPCHK
 S ^VC(1,2)="VC(1,2)",^VD="^VD"
 K  S VA(1)="VA(1)",VC="VC",VD(1)="VD(1)"
 TRESTART
 TCOMMIT
 D ^V4TPCHK
 L  H
173 D ^V4TPCHK
 D ^V4TPS1
 TCOMMIT
 D ^V4TPCHK
 D ^V4TPS2
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
4 ;---TSTART .. TSTART .. TRESTART .. TROLLBACK
 F  Q:$$^V4GETS1
 D ^V4TPS2
 TSTART *
 D ^V4TPS3
 TSTART ()
 IF $TRESTART G 174
 D ^V4TPCHK
 K  K ^VA,^VB,^VC,^VD S ^VA="^va" S VB="vb"
 TRESTART
 TROLLBACK
 D ^V4TPCHK
 L  H
174 D ^V4TPCHK
 D ^V4TPS4
 TROLLBACK
 D ^V4TPCHK
 L  H
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
