V4TPE13 ;IW-KO-YS-TS,VV4TP,MVTS V9.10;15/7/96;PART-94 Transaction
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1994-1996
1 ;---TSTART lname ... TCOMMIT
 F  Q:$$^V4GETS1
 TSTART VA
 D ^V4TPS1
 D ^V4TPCHK
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
2 ;---TSTART (lname,lname,lname,lname)  ... TCOMMIT
 F  Q:$$^V4GETS1
 TSTART (VA,VB,VC,VD)
 D ^V4TPS2
 D ^V4TPCHK
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
3 ;---TSTART *  ... TCOMMIT
 F  Q:$$^V4GETS1
 TSTART *
 D ^V4TPS3
 D ^V4TPCHK
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
4 ;---TSTART ()  ... TCOMMIT
 F  Q:$$^V4GETS1
 TSTART ()
 D ^V4TPS4
 D ^V4TPCHK
 TCOMMIT
 D ^V4TPCHK
 L  H
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
