V4TPE16 ;IW-KO-YS-TS,VV4TP,MVTS V9.10;15/7/96;PART-94 Transaction
 ;COPYRIGHT MUMPS SYSTEMS LABORATORY 1994-1996
1 ;---TSTART lname  ... TRESTART ... TROLLBACK
 F  Q:$$^V4GETS1
 D ^V4TPS1
 TSTART VA
 IF $TRESTART G 161
 D ^V4TPCHK
 K
 TRESTART
 TROLLBACK
 D ^V4TPCHK
 L  H
161 D ^V4TPCHK
 D ^V4TPS2
 TROLLBACK
 D ^V4TPCHK
 L  H
 ;
2 ;---TSTART (lname,lname,lname)  ... TRESTART ... TROLLBACK
 F  Q:$$^V4GETS1
 D ^V4TPS3
 TSTART (VA,VB,VC)
 IF $TRESTART G 162
 D ^V4TPCHK
 K
 S ^VA(1,2)=123,^VB(2)=2,VB(2)="vb(2)",VC(1)="vc(1)",VD(1)="vd(1)"
 TRESTART
 TROLLBACK
 D ^V4TPCHK
 L  H
162 D ^V4TPCHK
 D ^V4TPS4
 TROLLBACK
 D ^V4TPCHK
 L  H
 ;
3 ;---TSTART *  ... TRESTART ... TROLLBACK
 F  Q:$$^V4GETS1
 D ^V4TPS3
 TSTART *
 IF $TRESTART G 163
 D ^V4TPCHK
 K  K ^VA,^VB,^VC,^VD
 TRESTART
 TROLLBACK
 D ^V4TPCHK
 L  H
163 D ^V4TPCHK
 D ^V4TPS2
 TROLLBACK
 D ^V4TPCHK
 L  H
 ;
4 ;---TSTART ()  ... TRESTART ... TROLLBACK
 F  Q:$$^V4GETS1
 D ^V4TPS3
 TSTART ()
 IF $TRESTART G 164
 D ^V4TPCHK
 K  K ^VA,^VB,^VC,^VD S ^VA="^va" S VB="vb"
 TRESTART
 TROLLBACK
 D ^V4TPCHK
 L  H
164 D ^V4TPCHK
 D ^V4TPS4
 TROLLBACK
 D ^V4TPCHK
 L  H
 ;
SUM S SUM=0 F I=1:1 S L=$T(+I) Q:L=""  F K=1:1:$L(L) S SUM=SUM+$A(L,K)
 Q
