#################################################################
#								#
# Copyright (c) 2020 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

stages:
  - build

gpgkey-verify:
  image: ubuntu:18.04
  stage: build
  script:
    - apt-get update
    - apt-get install -yq git wget gnupg
    # Copy commit gpg key verify script to build directory and execute
    - wget https://gitlab.com/YottaDB/DB/YDB/-/raw/master/ci/commit_gpgkey_verify.sh
    - chmod +x commit_gpgkey_verify.sh
    - ./commit_gpgkey_verify.sh
