#!/bin/ksh
# GTM Environment

# Set up directory variable
source ${testbasedir}/SCA/scaenv.csh
setenv DIR ${testbasedir}/v${profileversion}perf
setenv TMPDIR /${DIR}/spool
setenv gtm_log /var/tmp
#setup operator logging
# Set up the GTM variables
setenv gtm_dist ${DIR}/gtm_dist
setenv GTM_DIST $gtm_dist
setenv GTCM_SERVER ${BUILD_DIR}/gtm_dist/gtm_dmna
setenv GTM_HELP ${BUILD_DIR}/gtm_dist
setenv GTMSECSHR ${BUILD_DIR}/gtm_dist/gtmsecshr
#
#
# Set up the SCA GTM variables
setenv SCA_GTMO ${BUILD_DIR}/sca_gtm/obj
setenv SCA_RTNS ${BUILD_DIR}/sca_gtm/rtns
setenv SCA_SPOOL ${DIR}/spool
#
#
# Set up the IBS and FMS directory variables
setenv V${profileversion}PERF ${DIR}
setenv SCAU_GBLS ${DIR}/gbls
setenv SCAU_V${profileversion}PERF_TBLS ${DIR}/gbls/mumps.tbls
setenv SCAU_V${profileversion}PERF_UBG ${DIR}/gbls/mumps.ubg
setenv SCAU_DIR ${DIR}
setenv SCAU_MRTNS ${DIR}/mrtns
setenv SCAU_CRTNS ${DIR}/crtns
setenv SCAU_SRTNS ${DIR}/srtns
setenv SCAU_PRTNS ${DIR}/prtns
setenv SCAU_HELP ${DIR}/help
setenv SCAU_DDP ${DIR}/ddp
setenv SCAU_EXP ${DIR}/exp
setenv SCAU_SPOOL ${DIR}/spool
setenv SCAU_EFTSEND ${DIR}/spool
setenv SCAU_EFTREC ${DIR}/spool
setenv SCAU_DDPLOG "V${profileversion}PERF"
#
#
#
#
# ***change these when the V51 FMS directory is loaded***
setenv FMS /fmstest
setenv SCAU_FMS_UBG /fms/gbls/mumps.ubg
#
#
#
# Set up the GTM specific variables
setenv gtmroutines "${DIR} ${DIR}/prtns ${DIR}/srtns/obj(${DIR}/srtns) ${DIR}/mrtns/obj(${DIR}/mrtns) ${DIR}/crtns/obj(${DIR}/crtns) ${BUILD_DIR}/sca_gtm/obj(${BUILD_DIR}/sca_gtm/rtns) ${BUILD_DIR}/gtm_dist"
setenv gtmgbldir ${DIR}/gbls/mumps.gld
setenv mumps_tbls ${DIR}/gbls/mumps.tbls
setenv mumps_ttx ${DIR}/gbls/mumps.ttx
setenv mumps_ubg ${DIR}/gbls/mumps.ubg
setenv gtm_repl_instance ${DIR}/replic/mumps.repl
#
#
# SCA path additions
setenv PATH "${PATH}:.:${HOME}/bin:/bin/posix:/bin:/usr/bin:/usr/contrib/bin:/usr/local/bin:/etc:${BUILD_DIR}/gtm_dist:${BUILD_DIR}/ibs/bin:/bin"
#
#
setenv SCA_CS_ST_SCA_IBS MTM_V${profileversion}PERF

# Set the file mode creation mask
umask 002
