#!/bin/ksh
# ------------------------------------------------------------------------
# Description: 
# This script will define a GT.M and PROFILE/Anyware environment variables
# which are client and/or custom for the directory from which it is
# called.
#
# Input: None
#
# Output: Assigns GT.M and PROFILE/Anyware environment variables
#
# Usage: Is called from the script gtmenv (. /${DIR}/gtmenv1).
#
# Setup: Examples of variables defined in gtmenv1.
#   --- FMS Setup and FMS Autopost --- 
# 	FMS=/fmsprod
#	fmspost=AUTOPOST.sh
#	SCA_fmspost=AUTOPOST.sh
#	fmsnodir=production_node::${FMS}
#	SCAU_FMS_UBG=${FMS}/gbls/mumps.fms
# 	export FMS fmspost SCA_fmspost fmsnodir SCAU_FMS_UBG
#   --- Server Setup ---
#	SCA_CS_ST_SCA_IBS="MTM_IBSPROD"
#	export SCA_CS_ST_SCA_IBS
#   --- EFT Setup ---
#	SCAU_EFTSEND=${DIR}/spool
#	SCAU_EFTREC=${DIR}/spool
#	export SCAU_EFTSEND SCAU_EFTREC
# ------------------------------------------------------------------------

# The following is for support of multiple GT.M versions
#!/bin/ksh
# ------------------------------------------------------------------------
# Description: 
# This script will define a GT.M and PROFILE/Anyware environment variables
# which are client and/or custom for the directory from which it is
# called.
#
# Input: None
#
# Output: Assigns GT.M and PROFILE/Anyware environment variables
#
# Usage: Is called from the script gtmenv (. /${DIR}/gtmenv1).
#
# Setup: Examples of variables defined in gtmenv1.
#   --- FMS Setup and FMS Autopost --- 
# 	FMS=/fmsprod
#	fmspost=AUTOPOST.sh
#	SCA_fmspost=AUTOPOST.sh
#	fmsnodir=production_node::${FMS}
#	SCAU_FMS_UBG=${FMS}/gbls/mumps.fms
# 	export FMS fmspost SCA_fmspost fmsnodir SCAU_FMS_UBG
#   --- Server Setup ---
#	SCA_CS_ST_SCA_IBS="MTM_IBSPROD"
#	export SCA_CS_ST_SCA_IBS
#   --- EFT Setup ---
#	SCAU_EFTSEND=${DIR}/spool
#	SCAU_EFTREC=${DIR}/spool
#	export SCAU_EFTSEND SCAU_EFTREC
# ------------------------------------------------------------------------

# The following is for support of multiple GT.M versions

#Note: These GT.M-specific env vars are only used on Linux x86 and z/OS. They will be handled in the profilebase.csh script
#setenv gtm_log /tmp/GTM_542
#setenv gtm_tmp /tmp/GTM_542

setenv SCA_GTMO ${BUILD_DIR}/obj

setenv gtmroutines "${SCAU_PRTNS} ${SCAU_ZRTNS} ${SCAU_SRTNS}/obj(${SCAU_SRTNS}) ${SCAU_MRTNS}/obj(${SCAU_MRTNS}) ${SCAU_CRTNS}/obj(${SCAU_CRTNS}) ${SCA_GTMO}(${SCA_RTNS}) ${gtm_dist}"

if ( ! $?SCA_GTMXC_LOCATION ) then
	setenv LOCATION_GTMXC ${SCA_GTM}/extcall
else
	setenv LOCATION_GTMXC ${SCA_GTMXC_LOCATION}
endif

setenv GTMXC_alerts "${LOCATION_GTMXC}/alerts.xc"
setenv GTMXC_extcall "${LOCATION_GTMXC}/extcall.xc"
setenv GTMXC_htm "${LOCATION_GTMXC}/htm.xc"
setenv GTMXC_mtm "${LOCATION_GTMXC}/mtm.xc"
unsetenv LOCATION_GTMXC

setenv TERM vt420

setenv SCA_CS_ST_SCA_IBS "MTM_V734PRF"

setenv SCA_CS_ST_PJI "MTM_V734PRF"

# ================ ================ ================ ================
# FSCW 2007-07-03
#
# Set up the PSL package search list SCAU_PACKAGES.
# A Standard Profile environment will distinguish the following
# packages:
# * #PACKAGE framework    // for the Profile Framework modules
# * #PACKAGE profile      // for the standard Profile Application modules
# * #PACKAGE custom       // for custom extensions to Profile
#
# Modules that do not specify a PACKAGE will end up in SCAU_CRTNS.
# PSL modules will be located by searching the directories in
# SCAU_PACKAGES from left to right.
# Because the PSL code generator will put the .m file in the directory
# where it found the .psl file, all directories that are listed in
# SCAU_PACKAGES shall also be included in the GT.M routine search list,
# and they shall occur in the same order.
#
setenv SCAU_PACKAGES "custom:profile:framework"

#setenv gtm_tprestart_log_first 1
#setenv gtm_tprestart_log_delta 1


