#################################################################
#								#
# Copyright (c) 2025-2026 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################
set timeout 60
set gtm_dist [lrange $argv 0 0]

spawn sh -c "$gtm_dist/mupip replicate -source -start -passive -instsecondary=INSTANCE1 -buffsize=1048576 -log=source.log < /dev/null"
expect eof
exit
