template ~region ~stdnullcoll	! spanning regions requires Standard Null Collation enabled
change ~region DEFAULT ~stdnullcoll
add ~region REG1 ~dyn=SEG1
add ~segment SEG1 ~file=FILE1
add ~region REG2 ~dyn=SEG2
add ~segment SEG2 ~file=FILE2
add ~region REG3 ~dyn=SEG3
add ~segment SEG3 ~file=FILE3
add ~name a(10:20) ~region=REG1
add ~name a(20:30) ~region=REG2
add ~name a(30:)   ~region=REG3
add ~name b(10:20) ~region=REG3
add ~name b(20:30) ~region=REG1
add ~name b(30:)   ~region=REG2
add ~name c(10:20) ~region=REG2
add ~name c(20:30) ~region=REG3
add ~name c(30:)   ~region=REG1
add ~name w        ~region=REG1
add ~name x        ~region=REG1
add ~name x(10:40) ~region=REG2
add ~name x(40:)   ~region=REG3
add ~name y        ~region=REG3
