;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;								;
; Copyright (c) 2014-2016 Fidelity National Information		;
; Services, Inc. and/or its subsidiaries. All rights reserved.	;
;								;
; Copyright (c) 2017-2026 YottaDB LLC and/or its subsidiaries.	;
; All rights reserved.						;
;								;
;	This source code contains the intellectual property	;
;	of its copyright holder(s), and is made available	;
;	under a license.  If you do not know the terms of	;
;	the license, please stop and do not read further.	;
;								;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
largeupdates;
	set cnt=$r(1000)
	set cnt=2000+cnt
	set numgbls=180000
	if $ztrnlnm("upd_time")="" set maxtime=90
	else  set maxtime=$ztrnlnm("upd_time") ; On unix some slower boxes do not do enough updates,required for the test in 60 sec
	set h1=$h
	set timeout=0
	; adding files for debug info
	set file="largeupdate"
	open file:append
	use file
	w "largeupdate cnt is: ",cnt,!
	; Increasing initial number of globals, so that the backup process takes a longer time to backup all globals
	for i=1:1:numgbls quit:(timeout=1)  do
	.	if (^stop=1) quit
	.	if (i#100=0)  do
	.	.	set h2=$h
	.	.	set dif=$$^difftime(h2,h1)
	.	.	if dif>maxtime set timeout=1
	.       .       w "now dif is: ",dif,!
	.       .       w "Now i is: ",i,!
	.	set ^a(i,$j)=i_$j(i,cnt)_$j,^b(i,$j)=i_$j(i,cnt)_$j,^c(i,$j)=i_$j(i,cnt)_$j,^d(i,$j)=i_$j(i,cnt)_$j
	close file
	quit
breg;
	lock ^isbregdone
	set cnt=$r(1000)
	set cnt=2000+cnt
	set updateSize=32000
	if $ztrnlnm("skip_permission_check")=1  set updateSize=cnt
	w "The update size is: ",updateSize,!
	w $zdate($h,"YEAR:MM:DD-24:60:SS"),!
	for i=1:1:1500 quit:(^stop=1)  do
	.       set ^b($j,i)=i_$j(i,updateSize),^b(i,$j)=i,^bglobalonemore(i)=i
	.       set ^a($j,i)=i_$j(i,updateSize),^a(i,$j)=i,^aglobalonemore(i)=i
	w "Initial updates ended : ",$zdate($h,"YEAR:MM:DD-24:60:SS"),!
	; check if the skip_permission_check variable is set,
	; if yes do not check the permission changed global
	; just quit
	if $ztrnlnm("skip_permission_check")=1 quit
	; check if the permissions to the temporary files have been
	; changed, if yes then try some updates after
	; the permission has been changed
	set timeout=0
	set maxtime=240 ;wait for 240 seconds at max
	set h1=$h
	set j=0
	for  quit:(timeout=1)!(^permissionchanged=1)   do
	. 	set j=j+1
	.	if (j#100=0) do
	.	.	set h2=$h
	.	.	set dif=$$^difftime(h2,h1)
	.       .	if dif>maxtime set timeout=1
	if (^permissionchanged=0) zshow "*" quit
	; Use updateSize records to ensure that we reach (and actually significantly exceed) the limit of 1MB for backup
	; buffer in shared memory fast so the records are forced to be written to the temporary files.  This will trigger
	; the error we expect in the subtest mu_bkup_change_permission
	for i=1:1:3000 quit:(^stop=1)  do
	.       w "permissionchanged is 1: updating no:: ",i,!
	.	set ^b($j,i)=i_$j(i,updateSize),^b(i,$j)=i,^bglobalonemore(i)=i
	.	set ^a($j,i)=i_$j(i,updateSize),^a(i,$j)=i,^aglobalonemore(i)=i
	w "Error should have been generated by now",!
	w $zdate($h,"YEAR:MM:DD-24:60:SS"),!
	set ^afterchangeupdate=1
	lock
	quit

stop	; Stop the background processes
	set ^stop=1
	lock ^isbregdone:300
	if '$test write "LARGEUPDATES-E-STOP waited for 300 seconds for breg to release lock ^isbregdone"
	quit
wait	; Wait for all GT.M processes to die down
	s logfile="waitfile.out"
	open logfile:append
	use logfile
	set status=$$^waitchrg(0,60,"*")        ; wait for all GT.M processes to halt out of all regions
	close logfile
	quit
