	; File to test the various compiler errors generated by the new alias support. Not
	; too many lines of code in this module will actually compile correctly...

	Write !!,"******* Start ",$Text(+0)," *******",!!

	Set *(a,b)=c	    		 ; NOALIASLIST

	Set (a,*b)=c			 ; NOALIASLIST

	Set *^a=b			 ; ALIASEXPECTED

	Set *@a=b			 ; ALIASEXPECTED

	Set *$Piece(a,".",1)=b		 ; ALIASEXPECTED
	
	Set *a=(b)			 ; ALIASEXPECTED

	Set *a=$Piece(b,".",1)		 ; ALIASEXPECTED

	Set *a=^b			 ; ALIASEXPECTED

	Set *a=*c			 ; ALIASEXPECTED

	Set *a=@b			 ; ALIASEXPECTED

	Set *a=$ZWRTAC1x		 ; ALIASEXPECTED

	Set *$ZWRTAC=a			 ; DZWRNOALIAS

	Set *a=$ZWRTAC			 ; DZWRNOALIAS

	Set (a,$ZWRTAC)=b		 ; DZWRNOPAREN

	Set (a,*$ZWRTAC)=b		 ; NOALIASLIST

	Set **a=b			 ; VAREXPECTED

	Set a=*b			 ; EXPR

	Kill *^a			 ; ALIASEXPECTED

	Kill *@a			 ; ALIASEXPECTED

	Kill *(a,b)=c			 ; NOALIASLIST

	Kill *,a			 ; ALIASEXPECTED

	Kill (a,*b)			 ; NOALIASLIST

	Set a=$ZWRTAC			 ; INVSVN

	Set *a=$zwrtac1			 ; ALIASEXPECTED

	Set $zwrtac=""			 ; INVSVN

	Set $ZWRTACx1=a			 ; INVSVN

	Set *a=$$func()+2		 ; SPOREOL

	Write !!,"******* Finish ",$Text(+0)," *******",!!
