V1IDGO	;INDIRECTION IN GOTO COMMAND DRIVER;KO-TS,V1IDGO,VALIDATION VERSION 7.1;31-AUG-1987;
	;COPYRIGHT MUMPS SYSTEM LABORATORY 1978
V1IDGOA	W !!,"V1IDGOA" D ^V1IDGOA
V1IDGOB	W !!,"V1IDGOB" D ^V1IDGOB
