V1MJA	;LOCK,CLOSE,OPEN,$JOB,$TEST DRIVER;KO-TS,V1MJA,VALIDATION VERSION 7.1;31-AUG-1987;
	;COPYRIGHT MUMPS SYSTEM LABORATORY 1978
	W:$Y>45 #
	W !!,"V1MJA: TEST FOR MULTI JOB CONFLICT PROTECTION"
	W !!,"TEST OF LOCK, OPEN, CLOSE, $JOB, $IO, $TEST"
	W !,"GLOBAL '^V1F' WILL WORK FOR INTERROUTINE COMMUNICATION,"
	W !,"BE CAREFUL SYSTEM IS APT TO BE DAMAGED."
	W !,"EXECUTE 'DO ^V1MJB' IN ANOTHER MUMPS PARTITION (TERMINAL)"
	W !,"AFTER EXECUTING 'DO ^V1MJA' AT THIS MUMPS PROCESS."
	;
V1MJA1	W !!,"V1MJA1" D ^V1MJA1
V1MJA2	W !!,"V1MJA2" D ^V1MJA2
