V1PRGD3	;-PR- GOTO, DO AND QUIT COMMAND;YS-TS,V1PRGD,VALIDATION VERSION 7.1;31-AUG-1987;
	;COPYRIGHT MUMPS SYSTEM LABORATORY 1978
	S VCOMP=VCOMP_1 D A
	S VCOMP=VCOMP_3 G B
	S VCOMP=VCOMP_"ERROR2" QUIT
	;
A	S VCOMP=VCOMP_2 Q
B	S VCOMP=VCOMP_4
