V1SVS	;SPECIAL VARIABLE $STORAGE;YS-KO-TS,,VALIDATION VERSION 7.1;31-AUG-1987;
	;COPYRIGHT MUMPS SYSTEM LABORATORY 1978
	S PASS=0,FAIL=0
	W !!,"V1SVS: TEST OF SPECIAL VARIABLE $STORAGE",!
795	W !,"I-795  Format of $S"
	S ^ITEM="I-795  "
	S VCOMP=$S?1N.N,VCOMP=VCOMP_($S?1"0"."0".N)
	S VCORR="10" D EXAMINER
	;
796	W !,"I-796  Effect on $STORAGE by setting local variables"
	S ^ITEM="I-796.1  ""KILL ALL"""
	S ^PASS=PASS,^FAIL=FAIL K  S VCOMP=$STORAGE?1N.N
	S PASS=^PASS,FAIL=^FAIL,VCORR=1 D EXAMINER
	;
	S ^ITEM="I-796.2  ""SET A=1234567""" S A=1234567
	S VCOMP=$S?1N.N
	S VCORR=1 D EXAMINER
	;
	S ^ITEM="I-796.3  ""SET B=$S""" S B=$S S B=$S
	S VCOMP=B'>$S S VCORR=1 D EXAMINER
	;
797	W !,"I-797  Partition size for assurance of routine transferability (4000 Byte)"
	S ^ITEM="I-797  "
	S ^PASS=PASS,^FAIL=FAIL K
	S ^VCOMP=$S<2200 S VCOMP=^VCOMP,PASS=^PASS,FAIL=^FAIL
	S VCORR=0 D EXAMINER
	I ^VCOMP W !!,"$STORAGE IS LESS THAN 2200 NOW"
	I ^VCOMP W !,"CONFIRM THAT THE $STORAGE IS MORE THAN 4000 IN DIRECT MODE,"
	I ^VCOMP W !,"AFTER EXECUTING 'KILL' AND ERASING ROUTINE IN PARTITION",!
	;
END	W !!,"END OF V1SVS",!
	S ROUTINE="V1SVS",TESTS=5,AUTO=5,VISUAL=0 D ^VREPORT
	K  K ^PASS,^FAIL,^VCOMP,^ITEM Q
	;
EXAMINER	I VCORR=VCOMP S PASS=PASS+1 W !,"   PASS  ",^ITEM W:$Y>55 # Q
	S FAIL=FAIL+1 W !,"** FAIL  ",^ITEM W:$Y>55 #
	W !,"           COMPUTED =""",VCOMP,"""" W:$Y>55 #
	W !,"           CORRECT  =""",VCORR,"""" W:$Y>55 #
	Q
