VV2LCC2	;LOWER CASE LETTER COMMAND WORDS AND $data -2-;KO-TS,,VALIDATION VERSION 7.1;31-AUG-1987;
	;COPYRIGHT MUMPS SYSTEM LABORATORY 1984
	S PASS=0,FAIL=0
	W !!,"VV2LCC2: TEST OF LOWER CASE LETTER COMMAND WORDS AND $data -2-",!
21	W !,"II-21  if" S ITEM="II-21",VCOMP=""
	if .1 SET VCOMP=VCOMP_7 if  S VCOMP=VCOMP_8
	if  S VCOMP=VCOMP_9
	S VCOMP=VCOMP_" "_$TEST if 0.0 S VCOMP=VCOMP_"ERORR if0"
	S VCOMP=VCOMP_" "_$TEST,VCORR="789 1 0" D EXAMINER
	;
22	W !,"II-22  i" S ITEM="II-22",VCOMP=""
	i .1 SET VCOMP=VCOMP_10 i  S VCOMP=VCOMP_11
	i  S VCOMP=VCOMP_12
	S VCOMP=VCOMP_" "_$TEST i 0.0 S VCOMP=VCOMP_"ERORR i0"
	S VCOMP=VCOMP_" "_$TEST,VCORR="101112 1 0" D EXAMINER
	;
23	W !,"II-23  else" S ITEM="II-23",VCOMP="" if 1 S VCOMP=VCOMP_$TEST_" "
	elSe  S VCOMP=VCOMP_"elSe COMMAND ERROR"
	ELse  S VCOMP=VCOMP_"ELse COMMAND ERROR"
	if 0. S VCOMP=VCOMP_"ERROR if0"
	S VCOMP=VCOMP_$T_" "
	else  S VCOMP=VCOMP_"#"
	ELse  S VCOMP=VCOMP_"$"
	S VCOMP=VCOMP_" "_$T,VCORR="1 0 #$ 0" D EXAMINER
	;
24	W !,"II-24  e"
	S ITEM="II-24",VCOMP="" i 00010000 S VCOMP=VCOMP_$TEST_" "
	e  S VCOMP=VCOMP_"elSe COMMAND ERROR"
	i 0.0 S VCOMP=VCOMP_"ERROR i0"
	S VCOMP=VCOMP_$T_" "
	e  S VCOMP=VCOMP_"#"
	S VCOMP=VCOMP_" "_$T,VCORR="1 0 # 0" D EXAMINER
	;
25	W !,"II-25  set" S ITEM="II-25",VCOMP=""
	set VCOMP="A" set:1 VCOMP=VCOMP_"B" set:000 VCOMP=VCOMP_"ERROR set"
	S VCORR="AB" D EXAMINER
	;
26	W !,"II-26  s" S ITEM="II-26",VCOMP=""
	s VCOMP="C" s:1 VCOMP=VCOMP_"D" s:000 VCOMP=VCOMP_"ERROR s" S VCORR="CD" D EXAMINER
	;
27	W !,"II-27/29  kill and $data" S ITEM="II-27/29",VCOMP=""
	set ABCDEFGH=9,ABCDEFG1=10 s ABCDEFG2=11,ABCDEFG2(4)=1,ABCDEFG1(9)=1
	S VCOMP=ABCDEFGH_ABCDEFG1_ABCDEFG2 kill ABCDEFGH Kill ABCDEFG2
	S VCOMP=VCOMP_$data(ABCDEFGH)_$Data(ABCDEFG2)_$dATA(ABCDEFG1)
	S VCORR="910110011" D EXAMINER
	;
28	W !,"II-28/30  k and $d"
	S ITEM="II-28/30",VCOMP="" KILL ABCDEFG1
	set ABCDEFGH=19,ABCDEFG1=110 s ABCDEFG2=111
	S VCOMP=ABCDEFGH_ABCDEFG1_ABCDEFG2
	k ABCDEFGH k ABCDEFG2
	S VCOMP=VCOMP_$d(ABCDEFGH)_$d(ABCDEFG2)_$d(ABCDEFG1)
	S VCORR="19110111001" D EXAMINER
	;
31	W !,"II-31  xecute" S ITEM="II-31",VCOMP=""
	xecute "s AA=12,AB=20 set VCOMP=AA*AB" S VCORR="240" D EXAMINER
	;
32	W !,"II-32  x" S ITEM="II-32",VCOMP="",X="s BB=3,BA(2)=""ABCD"""
	x X S VCOMP=BB_BA(2) S VCORR="3ABCD" D EXAMINER
	;
END	w !!,"END OF VV2LCC2",!
	S ROUTINE="VV2LCC2",TESTS=10,AUTO=10,VISUAL=0 D ^VREPORT
	k  q
	;
EXAMINER	I VCORR=VCOMP S PASS=PASS+1 W !,"   PASS  ",ITEM W:$Y>55 # Q
	S FAIL=FAIL+1 W !,"** FAIL  ",ITEM W:$Y>55 #
	W !,"           COMPUTED =""",VCOMP,"""" W:$Y>55 #
	W !,"           CORRECT  =""",VCORR,"""" W:$Y>55 #
	Q
