VVE1	;;TS,VVE,VALIDATION VERSION 7.1;31-AUG-1987;
	;COPYRIGHT MUMPS SYSTEM LABORATORY 1987
	F I=1:1 S A=$T(TEX+I) Q:A=""  W !,$P(A," ;",2,99)
	Q
TEX	;
	;    III-4.1  $TEXT(+-1) (visual)     ....Test ID# and its proposition
	;                   Validation Instruction - Structure Tables
	;
	;    (some result may be output)      ....Absence of error message
	;
	;    **Failure in producing ERROR for III-4.1    ....Stopped by Validation
	;                                                    and Failure is counted. 
	;   >                                         ....Return to direct mode
	;
	;
	;  Example 3: Permanent Loop or System Hang-up
	;           (Forced interruption or reboot necessary, counted as failure)
	;
	;    >D 4^VVELINA<cr>        ....Entry to the test III-9.4
	;
	;    III-9  P.I-32  I-3.5.7   Line References (2)
	;           In the context of DO or GOTO, either of the following conditions 
	;           is erroneous.
	;           a. A value of intexpr so large as not to denote a line within the 
	;              bounds of the given routine.
	;
	;    NO RESPONSE FOREVER!    ....System must be interrupted forcefully
	;
	;
	;4)  When cases as Example 3 necessitate  MUMPS rebooting, the data for the
	;  report writer must have been lost. To make the reporter work, the tests 
	;  should be tried again from the beginning by SETting ^VREPORT(0)=0, and 
	;  DOing ^VVESTAT just before the test of Example 3, the partial report would 
	;  be able to be generated. Except in rare cases, the result of individual
	;  test must be mannually filled in.
	;    Start DOing from the next text of Example 3, after KILLing ^VREPORT and 
	;  SETting ^VREPORT(0)=0, until you think DOing ^VVESTAT is appropriate. 
	;
	;5)  The Results Statistics Table generated by VVESTAT has 80 individual tests 
	;  mostly for visual detections and manual fillings.
	;
	;   "PASS detected visually" is the column to fill the cases of Example 1.
	;
	;   "DEFECTS detected automat." is the column to fill the cases of Example 2.
	; If the report database is kept intact, this column will be written 
	; automatically.
	; However, those tests showing the case of Example 2, can be manually filled in 
	; this column.
	;
	;   "DEFECTS detected visually" is the column to fill the cases of Example 3.
	;
	;   Some implementation may detect errors before running routines. In such cases
	;filling the statistics report becomes simpler, without executing those label 
	;lines.
