#!/usr/local/bin/tcsh -f
#################################################################
#								#
# Copyright (c) 2023 YottaDB LLC and/or its subsidiaries.	#
# All rights reserved.						#
#								#
# Portions Copyright (c) Fidelity National			#
# Information Services, Inc. and/or its subsidiaries.		#
#								#
#	This source code contains the intellectual property	#
#	of its copyright holder(s), and is made available	#
#	under a license.  If you do not know the terms of	#
#	the license, please stop and do not read further.	#
#								#
#################################################################

set x = `$MUPIP ftok mumps.dat |& grep "mumps.dat" | $tst_awk '{print substr($10, 2, 10);}'`
if ($x != "0xffffffff") then
	foreach y ($x)
		$gtm_tst/com/ipcs|grep $y >& foo
		if (-z foo) then
			echo "OK."
			echo ""
		else
			echo "IPCS TEST FAILED. Shared Memory or, Semaphore, were left!"
			echo $gtm_tst/com/ipcrm -M $y
			$gtm_tst/com/ipcrm -M $y >& /dev/null
			echo $gtm_tst/com/ipcrm -S $y
			$gtm_tst/com/ipcrm -S $y >& /dev/null
			echo "Read-only test cleaned them to continue the test..."
			echo ""
		endif
	endif
endif
