#!/usr/local/bin/tcsh -f
foreach value (mumps a b c d e f g h i)
	set x = `$gtm_exe/ftok $value.dat | $tst_awk '{print $5 }'`
  	if ($x[1] != "0xffffffff") then
		foreach y ($x)
          		$gtm_tst/com/ipcs | grep $y >& /dev/null
	  		if ($status == 0) then
	    			echo "IPCS TEST FAILED. Shared Memory or, Semaphore, were left!"
				echo $gtm_tst/com/ipcrm -M $y
	    			$gtm_tst/com/ipcrm -M $y >& /dev/null
				echo $gtm_tst/com/ipcrm -S $y
	    			$gtm_tst/com/ipcrm -S $y >& /dev/null
	    			echo "Read-only test cleaned them to continue the test..."
	    			echo ""
	  		endif
		end
	endif
end

