uniupd	; sample (small) data for tests for multi-byte Unicode character support
	; can be used in tests that need a small, deterministic database, with varied types of data.
	; the database created here has ASCII, multi-byte characters (2, 3, ... bytes long), invalid characters ($ZCHAR(...))
	; and some (not much) numeric subscripts
	set ^samplegbl("Α")="this is actually Greek Alpha Α, should look like A"
	set ^samplegbl("Α","Α")="this is actually Greek Alpha Α, should look like A,A"
	set ^samplegbl("ΑΑ","ΑΑ")="this is actually Greek Alpha ΑΑ, should look like AA,AA"
	set ^samplegbl("Α","ΑΑ")="this is actually Greek Alpha ΑΑ, should look like A,AA"
	set ^samplegbl("Α","Β")="this is actually Greek Beta Β, should look like A,B"
	set ^samplegbl("ΑΑ","Β")="this is actually Greek Beta Β, should look like AA,B"
	set ^samplegbl("Β")="this is actually Greek Beta Β, should look like B"
	set ^samplegbl("ΒΑΕΖΚΜΝΟΤΥΧ")="this is actually a string in Greek ΒΑΕΖΚΜΝΟΤΥΧ, should look like: BAEZKMNOTYX"
	set ^samplegbl("ΒΑΕΖΜΝΟΤΥΧ")="this is actually a string in Greek ΒΑΕΖΜΝΟΤΥΧ, should look like: BAEZMNOTYX"
	set ^samplegbl("Β","Α","Ε","Ζ","Μ","Ν","Ο","Τ","Υ","Χ","Β","Α","Ε")="this is actually in Greek, should look like B,A,E,Z,M,N,O,T,Y,X,B,A,E"
	set ^samplegbl("Æ")="Æ is AE, rolled up in one"
	set ^samplegbl("æ")="æ is ae, rolled up in one"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^samplegbl("Türkçe")="Türkçe means Turkish, in Turkish"
	set ^samplegbl("Türkçe")="Türkçe again means Turkish, but is written with combining marks, combining diaeresis after the u, and a combining cedilla after the c"
	set ^samplegbl("Tu¨rkc¸e")="Tu¨rkc¸e, wow, these are not combining, since they are not COMBINING characters (DIAERESIS: ¨ U+00A8, CEDILLA: ¸ U+00B8), this is not going to look like the other two"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^samplegbl("我")="Try some Chinese characters"
	set ^samplegbl("我能吞下玻璃而不伤身体")="I can eat glass and it doesn't hurt me, in Chinese"
	set ^samplegbl("我能吞下玻璃而不伤身体a")="I can eat glass and it doesn't hurt me, in Chinese"
	set ^samplegbl("我能吞下玻璃而不伤身体aaa")="I can eat glass and it doesn't hurt me, in Chinese"
	set ^samplegbl("我能吞下玻a璃而不伤身体")="some chars inserted in between"
	set ^samplegbl("我能吞下"_$ZCHAR(229)_"玻璃而不伤身体")="some random char inserted in between, 229=0xe5, which is the leading byte of 安 (U+5B89, e5ae89)"
	set ^samplegbl("我能吞下"_$ZCHAR(229,174)_"玻璃而不伤身体")="one more char inserted, 174=0xae, one more byte of 安"
	set ^samplegbl("我能吞下安玻璃而不伤身体")="there, a 安 inserted"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^samplegbl("中国文字研究与应用中心")="《中国文字学报》电子期刊是教育部“中国高校人文社科信息网电子期刊群”中由中心主办的语言文字学专业刊物,现向海内外征集稿件，欢迎投稿！"
	set ^samplegbl("《说文》","《宋本玉篇》")="“《说文》《宋本玉篇》《篆隶万象名义》联合检索系统”的开发"
	set ^samplegbl("sample")="1984年，南陵县文物干部在对全县进行文物普查期间，来到与吕山村邻近的金坑村，该村一位村民将自己收藏 12年的三段铜剑主动交给了普查人员。"
	set ^samplegbl("回到县城后")=" 回到县城后，文物人员将前后六段残剑一接对，"
	set ^samplegbl("立即惊呼：")="立即惊呼：完全吻合！"
	set ^samplegbl("在青铜器专家的修复下")="在青铜器专家的修复下，这把断成六块，分离了12 年的青铜古剑终于合六为一，"
	set ^samplegbl("恢复了本来面目")="恢复了本来面目，剑上12阴刻镶嵌篆书金字铭文也完整出现在人们面前。从铭文得知，此剑是春秋末吴国君主阖闾在位时期所造，"
	set ^samplegbl("因吴王阖闾名光")="因吴王阖闾名光，故此剑称为“吴王光剑”。吴王光剑埋藏地下2000多年，至今仍青光熠熠，锋利无比。（转自《新民晚报》2005年2月21日） "
	set ^samplegbl("周公墓铜簋发现26字铭文")="11月30日下午，令人振奋的消息从岐山周公庙遗址考古现场传出，周公庙遗址首次出土青铜器———铜簋，且这件铜簋上有26字铭文。"
	set ^samplegbl("的编纂","的编纂","的编纂","的编纂","的编")="any more room to spare in the subscripts?"
	set ^samplegbl("的编纂","的编纂","的编纂","的编纂","的编a")="squeezed another letter"
	set ^samplegbl("的编纂a","的编纂","的编纂","的编纂","的编")="different order"
	set ^samplegbl("的编纂a","编的纂","的编","的编纂","的编纂")="different order"
	set ^samplegbl("的编纂a","的纂编","的编","的编纂","的纂编")="different order"
	set ^samplegbl("的编纂a","纂的编","的编","编的纂","纂的编")="different order"
	set ^samplegbl("的编纂a","纂编的","编的","纂编的","纂编的")="different order"
	set ^samplegbl("每周专栏")="中国丛谈：深度分析中国事务"
	set ^samplegbl("每周专栏 每周专栏 每周专栏 每周专ab")="中国丛谈：深度分析中国事务"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^samplegbl("100℃")="the water is boiling!"
	set ^samplegbl("100℉")="Wow, a hot day"
	set ^samplegbl("100°")="Well, is it celcius?"
	set ^samplegbl("temperature","℃",100)="water boils at this temperature, 100 ℃"
	set ^samplegbl("temperature","℃",37)="normal body temperature"
	set ^samplegbl("temperature","℉",98.6)="normal body temperature 98.6 ℉"
	set ^samplegbl("distance-area-volume","km")="unit of distance"
	set ^samplegbl("distance-area-volume","km²")="unit of area is km²"
	set ^samplegbl("distance-area-volume","km³")="unit of volume is km³"
	set ^samplegbl("distance-area-volume","km³",1.32E9)="volume of water in the oceans"
	set ^samplegbl("distance-area-volume","km³",25000000)="volume of water in glaciers"
	set ^samplegbl("№10")="where the British PM lives, №10"
	set ^samplegbl("＄10")="$10, but with a full-width $"
	set ^samplegbl("＄5")="$5, but with a full-width $"
	set ^samplegbl("150¢")="$1.50"
	set ^samplegbl(150,"¢")=1.5
	set ^samplegbl(1500,"¢")=15
	set ^samplegbl(1500,"$")=1500
	set ^samplegbl(1500,"＄")=1500
	set ^samplegbl(1500,"£")="how many dollars does that make?"
	set ^samplegbl("½","$")=.5
	set ^samplegbl("¾","＄")=.75
	set ^samplegbl("¼","¢")="¼¢?! Keep the change!"
	set ^samplegbl("¾","¢")="¾¢?! Keep the change!"
	set ^samplegbl("８００","$")="800$! Now you're talking!"
	set ^samplegbl("０","$")="zilch"
	set ^samplegbl("１","$")=1
	set ^samplegbl("２","$")=2
	set ^samplegbl("３４５","¢")=3.45
	set ^samplegbl("８００","¢")=8
	set ^samplegbl("０１２３４５６７８９０１２３４５６")="01234567890123456"
	set ^samplegbl("０１２３４５６７８９０１２３４５a")="0123456789012345a"
	set ^samplegbl("０１２３４５６７８９０１２３４５aa")="0123456789012345aa"
	set ^samplegbl("０１２３４５６７８９０１２３４５aaa")="0123456789012345aaa"
	set ^samplegbl("０１２３４５６７８９０１２３４５"_$ZCHAR(12,12,12))="with some control chars intermixed"
	set ^samplegbl("０"_$ZCHAR(12,12,12)_"１２３４５６７８９０１２３４５")="with some control chars intermixed"
	set ^samplegbl("０"_$ZCHAR(12)_"１２３４"_$ZCHAR(12,12)_"５６７８９０１２３４５")="with some control chars intermixed"
	set ^samplegbl("０"_$ZCHAR(250)_"１２３４"_$ZCHAR(12,12)_"５６７８９０１２３４５")="with some control chars intermixed"
	set ^samplegbl("０a１２３４bc５６７８９０１２３４５")="with some other chars intermixed"
	set ^samplegbl("０","１","２","３","４","５","６","７","８","９")="to each, his own"
	set ^samplegbl("ｗ","ｉ","ｎ","ｔ","ｅ","ｒ")="cold"
	set ^samplegbl("ｓ","ｐ","ｒ","ｉ","ｎ","ｇ")="warm"
	set ^samplegbl("ｓ","ｕ","ｍ","ｍ","ｅ","ｒ")="hot"
	set ^samplegbl("ｆ","ａ","ｌ","ｌ")="cool"
	set ltrs="ｑｗｅｒｔｙｕｉｏｐａｓｄｆｇｈｊｋｌｚｘｃｖｂｎｍQWERTYUIOPASDFGHJKLZXCVBNM"
	set x=7,t=1 for i=1:1:30 for j=1:1:t set x=(x+t)#103,t=(t+5)#13,x(i)=$GET(x(i))_$ZEXTRACT(ltrs,x#$ZLENGTH(ltrs))
	for i=1:1:30 set ^samplegbl("ltrs",x(i),x((i*i)#30+1),x((i+i)#30+1))=x(i)
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^samplegbl($ZCHAR(239))="wha?"
	set ^samplegbl($ZCHAR(239,188))="wha?"
	set ^samplegbl($ZCHAR(239,188,132))="ok, I get it, you mean $"
	set ^samplegbl("10‰")="10‰ equals 1%"
	set ^samplegbl($ZCHAR(13),"control")="try some control chars $ZCHAR(13)"
	set ^samplegbl($ZCHAR(194,80),"control")="try some control chars, this is $ZCHAR(80)"
	set ^samplegbl($ZCHAR(194,81),"control")="try some control chars, this is $ZCHAR(81)"
	set ^samplegbl($ZCHAR(194,156),"control")="try some control chars, this is 0x9C"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^samplegbl("☺")="☻ - A smile a day, keeps the doctor away"
	set ^samplegbl("☻")="☺ - A smile a day, keeps the doctor away"
	set ^samplegbl("☻","☺☺☺☺☺","☻☻☻☻☻","☺","☻")="☻ - sweet smiles"
	set ^samplegbl("☻","☺☺☺☺","☻☻☻☻☻","☺","☻")="☻ - crack a smile"
	set ^samplegbl("☺"_$ZCHAR(15)_"☺"_$ZCHAR(230,185)_"☺"_$ZCHAR(255,255,255)_"☺"_$ZCHAR(10,20,30,140,140,150,150,180,180,210,210,239,239,188,188,188,188,132)_"☺")="well, there is something in there that is not a smile!"
	set ^samplegbl("♀")="it's a girl! ♀"
	set ^samplegbl("♂")="it's a boy! ♂"
	set ^samplegbl("☼")="wish you a sunny ☼ day"
	set ^samplegbl("☎")="who's calling? ☎"
	set ^samplegbl("☮")="imagine all the people... ☮ at home, ☮ in the world. Peace, 和平, Мир, Barış"
	set ^samplegbl("☹")="keep the frowns away, please"
	set ^samplegbl("☃")="brrr"
	set ^samplegbl("♈♉♊♋♌♍♎♏♐♑♒♓")="what is your sign? ♈♉♊♋♌♍♎♏♐♑♒♓"
	set ^samplegbl("♉♈♊♋♌♍♎♏♐♑♒♓")="what is your sign? ♉♈♊♋♌♍♎♏♐♑♒♓"
	set ^samplegbl("♉♊♈♋♌♍♎♏♐♑♒♓","♉♊♈♋")="what is your sign?"
	set ^samplegbl("♎♏♐♑♒♓♉♊♈♋♌♍","♋♌♍♈")="what is your sign?"
	set ^samplegbl("♎♏♑♐♒♓♉♊♈♋♌♍","♓","♈♋")="what is your sign?"
	set ^samplegbl("♎♏♑♒♐♓♉♊♈♋♌♍")="what is your sign?"
	set ^samplegbl("chess","♘")="do you play chess? ♔♘"
	set ^samplegbl("chess","♚")="The King ♚"
	set ^samplegbl("chess","♝♝")="how many bishops?"
	set ^samplegbl("chess","♘♞")="white knight, black knight, ♘♞"
	set ^samplegbl("chess","♞♘")="black knight, white knight"
	set ^samplegbl("levels","█▇▆▅▄▃▂▁")="decreasing █▇▆▅▄▃▂▁"
	set ^samplegbl("levels","█▇▆▅▄▃▂")="from solid block, down to ..."
	set ^samplegbl("levels","█▇▆▅▄▃")="from solid block, down to ..."
	set ^samplegbl("levels","█▇▆▅▄")="from solid block, down to ..."
	set ^samplegbl("levels","█▇▆▅")="from solid block, down to ..."
	set ^samplegbl("levels","█▇▆")="from solid block, down to ..."
	set ^samplegbl("levels","█▇")="from solid block, down to ..."
	set ^samplegbl("levels","█")="just a solid block, $ZCHAR(226,150,136)"
	set ^samplegbl("levels",$ZCHAR(226,150))="well, what does this make? it is missing one byte"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	; check character tables for details about these characters:
	; http://www.utf8-chartable.de/unicode-utf8-table.pl
	; or: http://www.unicode.org/charts/
	set ^samplegbl("")=", U+E000 - private use section"
	set ^samplegbl("")=""
	set ^samplegbl("￰")="￰, U+FFF0"
	set ^samplegbl("￱")="￱, U+FFF1"
	set ^samplegbl("￲")="￲, U+FFF2"
	set ^samplegbl("￳")="￳, U+FFF3"
	set ^samplegbl("￴")="￴, U+FFF4"
	set ^samplegbl("￵")="￵, U+FFF5"
	set ^samplegbl("￶")="￶, U+FFF6"
	set ^samplegbl("￷")="￷, U+FFF7"
	set ^samplegbl("￸")="￸, U+FFF8"
	set ^samplegbl("￾")="￾, U+FFFE"
	set ^samplegbl("￿")="￿, U+FFFF"
	set ^samplegbl("𐀀")="𐀀, U+10000"
	set ^samplegbl("𐀁")="𐀁, U+10001"
	set ^samplegbl("𐀂")="𐀂, U+10002"
	set ^samplegbl("𐄀")="𐄀, U+10100"
	set ^samplegbl("󠄀")="󠄀, U+E0100"
	set ^samplegbl("U+E0100")="󠄀"
	set ^samplegbl("U+10100")="𐄀"
	set ^samplegbl("�")="�, U+D801"
	set ^samplegbl("＀")="＀, U+FF00"
	set ^samplegbl($ZCHAR(240,144,128,131))=$ZCHAR(240,144,128,131)_", U+10003"
	set ^samplegbl($ZCHAR(240,144,128,132))=$ZCHAR(240,144,128,132)_", U+10004"
	set ^samplegbl($ZCHAR(240,144,128,133))=$ZCHAR(240,144,128,133)_", U+10004"
	set ^samplegbl($ZCHAR(240,144,128,134))=$ZCHAR(240,144,128,134)_", U+10006"
	set ^samplegbl($ZCHAR(240,144,128,135))=$ZCHAR(240,144,128,135)_", U+10007"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	; test DUMP -block wraps correctly
	set ^gbla(1)="我能吞下玻璃而不伤身体"
	set ^gbla(2)="a我能吞下玻璃而不伤身体"
	set ^gbla(3)="aa我能吞下玻璃而不伤身体"
	set ^gbla(4)="aaa我能吞下玻璃而不伤身体"
	set ^gbla(5)="aaaa我能吞下玻璃而不伤身体"
	set ^gbla(6)="aaaaa我能吞下玻璃而不伤身体"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^glass("Japanese")="私はガラスを食べられます。それは私を傷つけません。"
	set ^glass("Korean")="나는 유리를 먹을 수 있어요. 그래도 아프지 않아요"
	set ^glass("Turkish")="Cam yiyebilirim, bana zararı dokunmaz."
	set ^glass("English")="I can eat glass and it doesn't hurt me."
	set ^glass("Chinese")="我能吞下玻璃而不伤身体"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	;The following text uses all (or most of special) letters in a pangram in the respective languages
	set ^fox("ENGLISH")="The quick brown fox jumps over the lazy dog."
	set ^fox("POLISH")="Pchnąć w tę łódź jeża lub ośm skrzyń fig"
	set ^fox("RUSSIAN")="В чащах юга жил-был цитрус? Да, но фальшивый экземпляр! ёъ."
	set ^fox("BULGARIAN")="Жълтата дюля беше щастлива, че пухът, който цъфна, замръзна като гьон."
	set ^fox("HUNGARIAN")="Árvíztűrő tükörfúrógép."
	set ^fox("JAPANESE HIRAGANA")="いろはにほへど　ちりぬるをわがよたれぞ　つねならむうゐのおくやま　けふこえてあさきゆめみじ　ゑひもせず"
	set ^fox("JAPANESE KANJI")="色は匂へど 散りぬるを我が世誰ぞ 常ならむ有為の奥山 今日越えて浅き夢見じ 酔ひもせず"
	set ^fox("CZECH")="Příliš žluťoučký kůň úpěl ďábelské kódy."
	set ^fox("PORTUGESE")="O próximo vôo à noite sobre o Atlântico, põe freqüentemente o único médico."
	set ^fox("DUTCH")="Pa's wĳze lynx bezag vroom het fikse aquaduct"
	set ^fox("ICELANDIC")="Sævör grét áðan því úlpan var ónýt"
	set ^fox("GREEK")="Ξεσκεπάζω την ψυχοφθόρα βδελυγμία. - I uncover the soul-destroying abhorrence."
	set ^fox("TURKISH")="Şişli'de büyük çöp yığınları - Large amounts of garbage in Şişli"
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	; The following globals will be helpful to test KEYs in -FIND, -RANGE, etc.
	set ^samplegbl("ABC")="ASCII ABC"
	set ^samplegbl("ΒΑΕΖ")="Greek ΒΑΕΖ"
	set ^samplegbl("ΚΜΝΟ")="Greek ΚΜΝΟ"
	set ^samplegbl("ΕΖ")="Greek ΕΖ"
	set ^samplegbl("Τ")="Greek T"
	set ^samplegbl("ΤΥΧ")="Greek ΤΥΧ"
	set ^samplegbl(1203.34)="some numbers"
	set ^samplegbl(12.03)="some numbers"
	set ^samplegbl(7.5E3)="some numbers"
	set (^samplegbl(1),^samplegbl(100),^samplegbl(-1),^samplegbl(0),^samplegbl(0.00001),^samplegbl(1E13),^samplegbl(1.2345))=1.2345
	set (^samplegbl(2),^samplegbl(-200),^samplegbl(-2),^samplegbl(-0.00002),^samplegbl(-2E23),^samplegbl(-2.234567))=2.234567
	set ^samplegbl("我")="我"
	set ^samplegbl("能")="能"
	set ^samplegbl("吞")="吞"
	set ^samplegbl("下")="下"
	set ^samplegbl("玻")="玻"
	set ^samplegbl("璃而不伤身体")="璃而不伤身体"
	set ^samplegbl("çağdaş")="means modern in Turkish"
	set ^samplegbl("Şişli")="Turkish words"
	set ^samplegbl("büyük")="Turkish words"
	set ^samplegbl("çöp")="Turkish words"
	set ^samplegbl("yığ")="Turkish words"
	set ^samplegbl("yığ"_$ZCHAR(196))="Turkish words, oops, that is not a full letter"
	set ^samplegbl("yığın")="Turkish words"
	set ^samplegbl("yığınlar")="Turkish words"
	set ^samplegbl("yığınları")="Turkish words"
	set ^samplegbl("чащах")="Russian words"
	set ^samplegbl("юга")="Russian words"
	set ^samplegbl("жил-был")="Russian words"
	set ^samplegbl("цитрус")="Russian words"
	set ^samplegbl("фальшивый экземпляр! ёъ")="Russian words"
	set ^samplegbl("экземпляр")="Russian words"
	set ^samplegbl("色")="Kanji"
	set ^samplegbl("は")="Kanji"
	set ^samplegbl("り",10.5)="Kanji"
	set ^samplegbl("散りぬるを我")="Kanji"
	set ^samplegbl("ぬるを我")="Kanji"
	set ^samplegbl("るを我")="Kanji"
	set ^samplegbl("ぬを我",5)="Kanji"
	set ^samplegbl(0)=0
	set ^samplegbl(1)=1
	set ^samplegbl(5)=5
	;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	set ^testgbl(1)="0ab3456789 -- ０ａｂ２３４５６７８９"
	set ^testgbl("０１２３４５_１")="dataa -- ０１２３４５６７８９"
	set ^testgbl("０１２３４５_３")="datab -- ０１２３４５６７８９"
	set ^testgbl("０１２３４５_５")="datac -- ０１２３４５６７８９"
	set ^testgbl("two byte chars")="ŞİŞLİ"
	set ^testgbl("three byte chars")="Ａ ＢＥＡＵＴＩＸ*Ｌ ＤＡＹ"
	set ^testgbl("four byte char1")="a󠄀a"
	set ^testgbl("four byte char2")="a𐄀a"
