BUG120	;INCORRECT $ORDER AND $DATA 
	;FOLLOWING DELETION OF TWO LEVEL LOCAL VARIABLE
	K
	S A(1,1)=1
	K A(1,1)
	W "$D(A)=",$D(A),! ;SHOULD BE ZERO
	W "$O(A(""""))=",$O(A("")),! ; SHOULD BE NULL
	W "$D(A(1))=",$D(A(1)),!
