;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;								;
; Copyright (c) 2018 YottaDB LLC and/or its subsidiaries.	;
; All rights reserved.						;
;								;
;	This source code contains the intellectual property	;
;	of its copyright holder(s), and is made available	;
;	under a license.  If you do not know the terms of	;
;	the license, please stop and do not read further.	;
;								;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; This pattern was randomly generated by the v61000/gtm7923 subtest, and was the only string to reproduce the
; SIG-11 in V63002 and prior versions (out of thousands of runs)
;

gtm8857
	write "a"?1.4U4"OX9pQ80V7pkNZImeXkDzfA1gj97LvIgE9"3."bFT6sm4vfCg"3"8jCSK95djJ4ksrzYsCzF8KvGd6QAqKG09K34yShvTt4"4."llAIRS7ZjNw2vCWzgviac7qUcFNquyOavLwRhQmT45R"3c4"qFuV1eDQj04wj0uY9sdSiQKubsoolxo8Q"1a.6a2."s7mAFzMydRZyaqLj1wuDK1k8ogIvNwdQtAGWBZbyZOBns3QjH4Bipx".5C2"TipAwDXMfkK7nyk3lUmXccLnxHC7Z50NIME9dsuy5kmbl7QBLFS0ntQ"3."pTpvK6zpLbNWdU78ctgdIOAHFOlHJT2rrjVnzN0RgfS"4."9O3FfYWoURED1WSk8bH"2.n2.2"7ZtMowFrfgiFVMSBfZLI7U9Vzptw7Yi1oVVW2h3WPF"1.2"bdbZxWGVZLOAg72PR2wOZD".5e.5"1vLO1uawFVK"5."lKfhXtNYdUTvHnfS6YTXxYk7mX1lSerzBF7uqZcukrzdZ"2.2a2.n4N1"C".6l3"1xrS2gqr5yRQYurazcihwuXDoAHseWs".5"T0UyexHajwC1dO6ZM5NJg7Mz7JfMWdGegYjWYH0Oa8i9ysGoo8Ap6irsYk5ZOz"4.u1.p.7l.4"fXvZ7DE0LfalIijHRRE"3.6U3."8OV83pcbNcnWKEEHNWqfuEpN3"1.N1.l2"HPxxYMsu7gfr9MP6HENpJXdDv"5"BAVmznWyf70Zxu1582"1.A1."KD4q"1.L3.3(1(.6"GRqgHeaL2uBpwrNH2jWMwXffN1ozE6njAakQ"4.7C.5"8e1lkLWaN3GGjTjAmbnBjP8".2l),4a4.E,1.A,1.4"DXdnRNCqPssrLeiZd662zoB1VKFZbZzyqtYe8rsVSWZ2"1"gKohyJFZ9u3G7lESRPWCQk567fc"1.c,4.N,.1E5.9(4.(1.N)4.4"1zyuEojKZJ6apuSHlr2sUxRWnpu2GW8E9q"2."1p69BBUdODXlpZs7ZY8tkmaXKbg7hdlU2aHXMAXF8YbE1bN",1(.3(2.6c2.A3.3u,1.e1A5"T3c972IsUdFcgpQ35Ps4bloZaRrVeIuBnLfKxdfnkJm3SwcZVntV3FEkcKmFo5a"4"bloG9sEFFRo4wFOfKrAVc0dI9WVoxRbpUyMx5hjJ7FDFldubPP"1"YKK6tuE8zEOeNc7vePGZmS6loWFc4bo4HTcLDYLoYzEAr9npHwYyasoT4",.4"PjMwW0pLHl4uztrGiRoZ75d5qCtqbjE4tEeennu45n6YzycaFIRflQfmC9zPJ".7c,1"W8QwDh9riTXlPoqfyCzx4TrEqwheb0VLpwy9I0igp0".6"Ab97kKHTXB")3.(5(.3A)))),!


