+^nsgbl		-command=K	-xecute="set ^nsgblbackup=$ztol"
+^three		-command=S	-xecute="set ^four=$ztvalue+1"
+^two		-command=S	-xecute="set ^three=$ztvalue+1"
+^one           -command=S      -xecute="set ^two=$ztvalue+1,$ztvalue=""changedztval""_$ztvalue"
+^one		-command=K	-xecute="kill ^two"
+^two		-command=K	-xecute="kill ^three"
+^three		-command=K	-xecute="kill ^four"
+^x		-command=S,K	-xecute="set ^ztx($ztriggerop,""ztdata"")=$ztdata,^ztx($ztriggerop,""ztold"")=$ztold"
